name: Run Forest Tests
on: [push, pull_request]
 
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Test with pytest
      working-directory: tests
      run: |
        pytest -m unittest
