name: Run Forest Tests
on: [push, pull_request]

jobs:
  test:
    name: Running Forest Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: "3.6"

      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          
      - name: testing forests
        run: 
          python -m pytest
