name: Run Forest Tests
on: [push, pull_request]

jobs:
  test:
    name: Running Forest Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: testing forests
        run: 
          python -m pytest
